# API Environment URLs
api.baseUrl=https://web.dev.trips.deluxe.com/receivables/trips
 
# Web Environment URLs
#web.baseUrl=https://web.dev.trips.deluxe.com/receivables/trips/trips-menu/login

web.baseUrl=https://legal.dev.trips.deluxe.com
 
# Default Company ID
default.companyID=0
 
# API User Credentials
api.username=testingXperts@trips.deluxe.com
api.password=6*Gs4d!C
 
# Web User Credentials
web.username=testingXperts@trips.deluxe.com
web.password=6*Gs4d!C
 
# Application Code
applicationCode=C	

# Test Data Source
testdata.APITestData=Data Files/API/APITestData.xlsx
testdata.WebTestData=Data Files/Web/WebTestData.xlsx

